### ISSUE TITLE
pin poetry version

### ISSUE THREAD

**Issue by julbright** [hkiang01/profile-decorator#1]
I'd recommend you pin a specific version of poetry in your toml's `build-backend` section. I've seen a few bugs pop up that are due to poetry version bumps. 1.16 or 1.1.7 seem like good candidates.

**Comment by hkiang01** [comment]
That would explain https://github.com/hkiang01/profile-decorator/runs/3456195539

**Comment by hkiang01** [comment]
I've tested poetry with the following versions, here are links to each corresponding run with working poetry versions:
- [1.1.8](https://github.com/hkiang01/profile-decorator/actions/runs/1180002656)
- [1.1.7](https://github.com/hkiang01/profile-decorator/actions/runs/1188026343)
- [1.1.6](https://github.com/hkiang01/profile-decorator/actions/runs/1188030643)
- [1.1.5](https://github.com/hkiang01/profile-decorator/actions/runs/1188033760)
- [1.1.4](https://github.com/hkiang01/profile-decorator/actions/runs/1188037280)
- [1.1.3](https://github.com/hkiang01/profile-decorator/actions/runs/1188043143)
- [1.1.2](https://github.com/hkiang01/profile-decorator/actions/runs/1188045424)
- [1.1.1](https://github.com/hkiang01/profile-decorator/actions/runs/1188047594)
- [1.1.0](https://github.com/hkiang01/profile-decorator/actions/runs/1188050023)
(I wanted to test them one at a time to "save runner cycles")

These versions don't work:
- [1.0.6-1.0.10](https://github.com/hkiang01/profile-decorator/runs/3478491776)
(I mean, I'm not paying for the runners, so why not lol)

Takeaway: pinning to the following:
```toml
[build-system]
requires = ["poetry-core>=1.1.0"]
```

**Comment by hkiang01** [comment]
fixed: https://github.com/hkiang01/profile-decorator/commit/941ef2cc2dceeead6c5cb990b03576af46675906
